<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../Alpha.Application/Alpha.Application.csproj" />
    <ProjectReference Include="../Alpha.Domain/Alpha.Domain.csproj" />
    <ProjectReference Include="../Alpha.Infrastructure/Alpha.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../docs/specifications/employer-interface/006/*.xsd.xml">
      <TargetPath>Specifications/EmployerInterface/006/%(Filename)%(Extension)</TargetPath>
      <Link>Specifications/EmployerInterface/006/%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
